//! Fixed-rate bond pricing and analytics, over a cashflow representation.
//!
//! A bond is modelled by its future cashflows `(time_in_years, amount)` measured
//! from the settlement date, plus the accrued interest at settlement. This keeps
//! the financial math pure and exactly validateable without reimplementing
//! calendar / schedule machinery (deferred): the cashflows can be generated by
//! [`FixedRateBond::regular`] for the common case, or supplied directly with
//! [`FixedRateBond::from_cashflows`].
//!
//! Two discounting modes:
//! - **Yield** — a flat yield-to-maturity compounded at the coupon frequency,
//!   `DF(t) = (1 + y/f)^(−f·t)` (the market / QuantLib `Compounded@freq`
//!   convention). Used for YTM, duration, and convexity.
//! - **Curve** — discount factors from an [`crate::curves::YieldCurve`] (continuous
//!   compounding), so a bond can be priced off a term structure.
//!
//! Prices are quoted per face; `clean = dirty − accrued`.

use crate::core::{OxisError, brent};
use crate::curves::YieldCurve;

/// A single future cashflow: `amount` paid at `time` years from settlement.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Cashflow {
    /// Time to payment in years (from settlement).
    pub time: f64,
    /// Cashflow amount (coupon, or coupon + redemption at maturity).
    pub amount: f64,
}

/// Compounded discount factor `(1 + y/f)^(−f·t)` at frequency `f`.
fn yield_discount(t: f64, y: f64, frequency: u32) -> Result<f64, OxisError> {
    let f = frequency as f64;
    let base = 1.0 + y / f;
    if base <= 0.0 {
        return Err(OxisError::numerical(
            "bond: yield below -frequency makes the discount base non-positive",
        ));
    }
    Ok(base.powf(-f * t))
}

/// Validate a cashflow slice: non-empty, finite, strictly increasing positive
/// times.
fn validate_cashflows(cfs: &[Cashflow]) -> Result<(), OxisError> {
    if cfs.is_empty() {
        return Err(OxisError::invalid_input("bond: no cashflows"));
    }
    if cfs
        .iter()
        .any(|c| !c.time.is_finite() || !c.amount.is_finite() || c.time <= 0.0)
    {
        return Err(OxisError::invalid_input(
            "bond: cashflow times must be finite and strictly positive, amounts finite",
        ));
    }
    if cfs.windows(2).any(|w| w[1].time <= w[0].time) {
        return Err(OxisError::invalid_input(
            "bond: cashflow times must be strictly increasing",
        ));
    }
    Ok(())
}

fn check_frequency(frequency: u32) -> Result<(), OxisError> {
    if frequency == 0 {
        return Err(OxisError::invalid_input("bond: frequency must be >= 1"));
    }
    Ok(())
}

/// Dirty (full) price as the present value of cashflows under a flat yield
/// compounded at `frequency`.
pub fn dirty_price_with_yield(cfs: &[Cashflow], y: f64, frequency: u32) -> Result<f64, OxisError> {
    validate_cashflows(cfs)?;
    check_frequency(frequency)?;
    let mut pv = 0.0;
    for c in cfs {
        pv += c.amount * yield_discount(c.time, y, frequency)?;
    }
    Ok(pv)
}

/// Dirty (full) price as the present value of cashflows discounted on a yield
/// curve (continuous compounding).
pub fn dirty_price_with_curve(cfs: &[Cashflow], curve: &YieldCurve) -> Result<f64, OxisError> {
    validate_cashflows(cfs)?;
    let mut pv = 0.0;
    for c in cfs {
        pv += c.amount * curve.discount(c.time)?;
    }
    Ok(pv)
}

/// Solve for the yield-to-maturity (compounded at `frequency`) that reprices the
/// cashflows to `dirty` (the full price).
///
/// # Errors
/// [`OxisError::Numerical`] if the price is not bracketed by a plausible yield
/// range or the solve does not converge.
pub fn yield_from_dirty(cfs: &[Cashflow], dirty: f64, frequency: u32) -> Result<f64, OxisError> {
    validate_cashflows(cfs)?;
    check_frequency(frequency)?;
    if !(dirty.is_finite() && dirty > 0.0) {
        return Err(OxisError::invalid_input("bond: price must be positive"));
    }
    // Price is monotonically decreasing in yield; bracket a wide plausible range.
    let f = |y: f64| dirty_price_with_yield(cfs, y, frequency).unwrap_or(f64::NAN) - dirty;
    brent(-0.9, 2.0, 1e-12, 200, f)
}

/// Macaulay duration: PV-weighted average time to cashflow, in years.
pub fn macaulay_duration(cfs: &[Cashflow], y: f64, frequency: u32) -> Result<f64, OxisError> {
    let p = dirty_price_with_yield(cfs, y, frequency)?;
    if p <= 0.0 {
        return Err(OxisError::numerical("bond: non-positive price in duration"));
    }
    let mut acc = 0.0;
    for c in cfs {
        acc += c.time * c.amount * yield_discount(c.time, y, frequency)?;
    }
    Ok(acc / p)
}

/// Modified duration: `Macaulay / (1 + y/f)`; the price sensitivity `−(1/P) dP/dy`.
pub fn modified_duration(cfs: &[Cashflow], y: f64, frequency: u32) -> Result<f64, OxisError> {
    let f = frequency as f64;
    Ok(macaulay_duration(cfs, y, frequency)? / (1.0 + y / f))
}

/// Convexity: `(1/P) d²P/dy²` under compounding at `frequency`.
pub fn convexity(cfs: &[Cashflow], y: f64, frequency: u32) -> Result<f64, OxisError> {
    let f = frequency as f64;
    let p = dirty_price_with_yield(cfs, y, frequency)?;
    if p <= 0.0 {
        return Err(OxisError::numerical(
            "bond: non-positive price in convexity",
        ));
    }
    let base = 1.0 + y / f;
    let mut acc = 0.0;
    for c in cfs {
        // d²/dy² (1+y/f)^(-f·t) = t·(t + 1/f)·(1+y/f)^(-f·t-2).
        acc += c.amount * c.time * (c.time + 1.0 / f) * base.powf(-f * c.time - 2.0);
    }
    Ok(acc / p)
}

/// A fixed-rate bond: its cashflows plus the accrued interest at settlement.
#[derive(Debug, Clone)]
pub struct FixedRateBond {
    /// Face / notional (redemption) amount.
    pub face: f64,
    /// Annual coupon rate (e.g. 0.05). Informational; the cashflows carry the
    /// actual coupon amounts.
    pub coupon_rate: f64,
    /// Coupon payments per year.
    pub frequency: u32,
    /// Future cashflows from settlement.
    cashflows: Vec<Cashflow>,
    /// Accrued interest at settlement (`clean = dirty − accrued`).
    pub accrued: f64,
}

impl FixedRateBond {
    /// Build a bond from explicit cashflows and accrued interest.
    ///
    /// `face`/`coupon_rate` are informational metadata for output; the cashflows
    /// are authoritative.
    pub fn from_cashflows(
        face: f64,
        coupon_rate: f64,
        frequency: u32,
        cashflows: Vec<Cashflow>,
        accrued: f64,
    ) -> Result<Self, OxisError> {
        validate_cashflows(&cashflows)?;
        check_frequency(frequency)?;
        if !accrued.is_finite() || accrued < 0.0 {
            return Err(OxisError::invalid_input(
                "bond: accrued must be finite and non-negative",
            ));
        }
        Ok(Self {
            face,
            coupon_rate,
            frequency,
            cashflows,
            accrued,
        })
    }

    /// Build a regular bond settling on a coupon date: `n_periods` equal coupons
    /// at `t = k/frequency`, each `face·coupon_rate/frequency`, plus `face`
    /// redeemed at the last. Accrued interest is zero.
    pub fn regular(
        face: f64,
        coupon_rate: f64,
        frequency: u32,
        n_periods: u32,
    ) -> Result<Self, OxisError> {
        check_frequency(frequency)?;
        if n_periods == 0 {
            return Err(OxisError::invalid_input("bond: need at least one period"));
        }
        if !(face.is_finite() && face > 0.0 && coupon_rate.is_finite()) {
            return Err(OxisError::invalid_input(
                "bond: face must be positive and coupon rate finite",
            ));
        }
        let f = frequency as f64;
        let coupon = face * coupon_rate / f;
        let cashflows = (1..=n_periods)
            .map(|k| {
                let redemption = if k == n_periods { face } else { 0.0 };
                Cashflow {
                    time: k as f64 / f,
                    amount: coupon + redemption,
                }
            })
            .collect();
        Self::from_cashflows(face, coupon_rate, frequency, cashflows, 0.0)
    }

    /// The bond's future cashflows (read-only view).
    pub fn cashflows(&self) -> &[Cashflow] {
        &self.cashflows
    }

    /// Dirty price from a flat yield.
    pub fn dirty_price_from_yield(&self, y: f64) -> Result<f64, OxisError> {
        dirty_price_with_yield(&self.cashflows, y, self.frequency)
    }

    /// Clean price from a flat yield (`dirty − accrued`).
    pub fn clean_price_from_yield(&self, y: f64) -> Result<f64, OxisError> {
        Ok(self.dirty_price_from_yield(y)? - self.accrued)
    }

    /// Yield-to-maturity from a quoted clean price.
    pub fn yield_to_maturity(&self, clean_price: f64) -> Result<f64, OxisError> {
        yield_from_dirty(&self.cashflows, clean_price + self.accrued, self.frequency)
    }

    /// Dirty and clean price discounted on a yield curve.
    pub fn price_from_curve(&self, curve: &YieldCurve) -> Result<(f64, f64), OxisError> {
        let dirty = dirty_price_with_curve(&self.cashflows, curve)?;
        Ok((dirty, dirty - self.accrued))
    }

    /// Macaulay duration at yield `y`.
    pub fn macaulay_duration(&self, y: f64) -> Result<f64, OxisError> {
        macaulay_duration(&self.cashflows, y, self.frequency)
    }

    /// Modified duration at yield `y`.
    pub fn modified_duration(&self, y: f64) -> Result<f64, OxisError> {
        modified_duration(&self.cashflows, y, self.frequency)
    }

    /// Convexity at yield `y`.
    pub fn convexity(&self, y: f64) -> Result<f64, OxisError> {
        convexity(&self.cashflows, y, self.frequency)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::curves::Interpolation;

    fn close(a: f64, b: f64, tol: f64) {
        assert!((a - b).abs() < tol, "{a} vs {b} (tol {tol})");
    }

    #[test]
    fn par_bond_prices_at_par() {
        // Coupon == yield => price == face.
        let bond = FixedRateBond::regular(100.0, 0.05, 2, 10).unwrap();
        close(bond.dirty_price_from_yield(0.05).unwrap(), 100.0, 1e-9);
        close(bond.clean_price_from_yield(0.05).unwrap(), 100.0, 1e-9);
    }

    #[test]
    fn zero_coupon_matches_closed_form() {
        let bond = FixedRateBond::regular(100.0, 0.0, 2, 6).unwrap(); // 3y, semiannual
        let y = 0.04;
        let expected = 100.0 / (1.0_f64 + y / 2.0).powf(6.0); // (1+y/f)^(f*T) = (1+y/2)^6
        close(bond.dirty_price_from_yield(y).unwrap(), expected, 1e-9);
    }

    #[test]
    fn ytm_round_trips() {
        let bond = FixedRateBond::regular(100.0, 0.06, 2, 8).unwrap();
        let clean = bond.clean_price_from_yield(0.045).unwrap();
        close(bond.yield_to_maturity(clean).unwrap(), 0.045, 1e-9);
    }

    #[test]
    fn regular_builds_expected_schedule() {
        let bond = FixedRateBond::regular(100.0, 0.05, 2, 4).unwrap();
        let cfs = bond.cashflows();
        assert_eq!(cfs.len(), 4);
        close(cfs[0].time, 0.5, 1e-15);
        close(cfs[0].amount, 2.5, 1e-15); // 100*0.05/2
        close(cfs[3].time, 2.0, 1e-15);
        close(cfs[3].amount, 102.5, 1e-15); // coupon + face
    }

    #[test]
    fn modified_is_macaulay_over_one_plus_y_over_f() {
        let bond = FixedRateBond::regular(100.0, 0.05, 2, 10).unwrap();
        let y = 0.05;
        let mac = bond.macaulay_duration(y).unwrap();
        let modd = bond.modified_duration(y).unwrap();
        close(modd, mac / (1.0 + y / 2.0), 1e-12);
        assert!(mac < 5.0, "duration {mac} should be below the 5y maturity");
        assert!(bond.convexity(y).unwrap() > 0.0);
    }

    #[test]
    fn curve_and_flat_yield_agree_for_matching_discounting() {
        // A flat continuous curve at r discounts e^{-r t}; pricing a zero-coupon
        // bond off it matches the closed form.
        let bond = FixedRateBond::regular(100.0, 0.0, 1, 5).unwrap();
        let curve = YieldCurve::flat(0.03).unwrap();
        let (dirty, _clean) = bond.price_from_curve(&curve).unwrap();
        close(dirty, 100.0 * (-0.03_f64 * 5.0).exp(), 1e-9);

        // Curve discounting also works with interpolated curves.
        let c2 = YieldCurve::from_zero_rates(
            &[1.0, 3.0, 5.0],
            &[0.02, 0.025, 0.03],
            Interpolation::Linear,
        )
        .unwrap();
        assert!(bond.price_from_curve(&c2).unwrap().0 > 0.0);
    }

    #[test]
    fn rejects_bad_inputs() {
        assert!(FixedRateBond::regular(100.0, 0.05, 0, 4).is_err()); // frequency 0
        assert!(FixedRateBond::regular(100.0, 0.05, 2, 0).is_err()); // no periods
        assert!(FixedRateBond::regular(-1.0, 0.05, 2, 4).is_err()); // negative face
        assert!(FixedRateBond::from_cashflows(100.0, 0.05, 2, vec![], 0.0).is_err());
        let bond = FixedRateBond::regular(100.0, 0.05, 2, 4).unwrap();
        assert!(bond.yield_to_maturity(-5.0).is_err()); // negative price
    }
}
