//! Validation of `oxis-stats` against a numpy / scipy / pandas oracle.
//!
//! QuantLib has thin coverage of return statistics and risk metrics, so the
//! oracle here is numpy/scipy/pandas — industry-standard, closed-form where
//! applicable. The reference values are generated by `validation/gen_stats()`
//! into `validation/reference/stats.json`; this test recomputes each metric with
//! the OXIS pure functions and asserts agreement within the file's tolerance
//! (with a looser band for the Jarque-Bera p-value).

use oxis_stats::{
    acf, annualized_return, annualized_volatility, beta, cornish_fisher_var, correlation,
    covariance, cumulative_return, excess_kurtosis, historical_es, historical_var,
    information_ratio, jarque_bera, max_drawdown, mean, parametric_es, parametric_var,
    sharpe_ratio, simple_returns, skewness, sortino_ratio, std_dev, tracking_error, variance,
};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct StatsFile {
    oracle: String,
    oracle_version: String,
    tolerance: f64,
    pvalue_tolerance: f64,
    cases: Vec<StatsCase>,
}

#[derive(Debug, Deserialize)]
struct StatsCase {
    name: String,
    returns: Option<Vec<f64>>,
    prices: Option<Vec<f64>>,
    values: Option<Vec<f64>>,
    benchmark: Option<Vec<f64>>,
    risk_free: f64,
    periods_per_year: f64,
    confidence: f64,
    acf_lags: Option<Vec<usize>>,
    acf: Option<Vec<f64>>,
    mean: Option<f64>,
    variance: Option<f64>,
    std_dev: Option<f64>,
    skewness: Option<f64>,
    excess_kurtosis: Option<f64>,
    jarque_bera: Option<f64>,
    jarque_bera_pvalue: Option<f64>,
    cumulative_return: Option<f64>,
    annualized_return: Option<f64>,
    annualized_volatility: Option<f64>,
    sharpe: Option<f64>,
    sortino: Option<f64>,
    historical_var: Option<f64>,
    historical_es: Option<f64>,
    parametric_var: Option<f64>,
    parametric_es: Option<f64>,
    cornish_fisher_var: Option<f64>,
    max_drawdown: Option<f64>,
    max_drawdown_duration: Option<usize>,
    calmar: Option<f64>,
    covariance: Option<f64>,
    correlation: Option<f64>,
    beta: Option<f64>,
    tracking_error: Option<f64>,
    information_ratio: Option<f64>,
}

fn load(name: &str) -> StatsFile {
    let path = format!(
        "{}/../../validation/reference/{}",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    let json = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read reference data at {path}: {e}"));
    serde_json::from_str(&json).expect("reference data is valid JSON")
}

#[test]
fn stats_match_numpy_scipy() {
    let reference = load("stats.json");
    assert_eq!(reference.oracle, "numpy/scipy/pandas");
    assert!(!reference.cases.is_empty());
    let tol = reference.tolerance;
    let ptol = reference.pvalue_tolerance;
    let mut worst = 0.0_f64;

    for case in &reference.cases {
        // Resolve the primary sample exactly as the binding/CLI does.
        let sample: Vec<f64> = if let Some(r) = &case.returns {
            r.clone()
        } else if let Some(v) = &case.values {
            v.clone()
        } else if let Some(p) = &case.prices {
            simple_returns(p).expect("derive returns from prices")
        } else {
            panic!("case {}: no sample input", case.name);
        };

        // A small closure to compare a present expected value against a computed
        // one, tracking the worst absolute error.
        let mut check = |name: &str, expected: Option<f64>, got: f64, tol: f64| {
            if let Some(exp) = expected {
                let err = (got - exp).abs();
                assert!(
                    err <= tol,
                    "case {}: {name} error {err:.3e} > {tol:.1e} (got {got}, want {exp})",
                    case.name
                );
                worst = worst.max(err);
            }
        };

        check("mean", case.mean, mean(&sample).unwrap(), tol);
        check("variance", case.variance, variance(&sample).unwrap(), tol);
        check("std_dev", case.std_dev, std_dev(&sample).unwrap(), tol);
        if case.skewness.is_some() {
            check("skewness", case.skewness, skewness(&sample).unwrap(), tol);
        }
        if case.excess_kurtosis.is_some() {
            check(
                "excess_kurtosis",
                case.excess_kurtosis,
                excess_kurtosis(&sample).unwrap(),
                tol,
            );
        }
        if case.jarque_bera.is_some() {
            let (jb, jbp) = jarque_bera(&sample).unwrap();
            check("jarque_bera", case.jarque_bera, jb, tol);
            check("jarque_bera_pvalue", case.jarque_bera_pvalue, jbp, ptol);
        }
        if case.cumulative_return.is_some() {
            check(
                "cumulative_return",
                case.cumulative_return,
                cumulative_return(&sample).unwrap(),
                tol,
            );
        }
        if case.annualized_return.is_some() {
            check(
                "annualized_return",
                case.annualized_return,
                annualized_return(&sample, case.periods_per_year).unwrap(),
                tol,
            );
        }
        if case.annualized_volatility.is_some() {
            check(
                "annualized_volatility",
                case.annualized_volatility,
                annualized_volatility(&sample, case.periods_per_year).unwrap(),
                tol,
            );
        }
        if case.sharpe.is_some() {
            check(
                "sharpe",
                case.sharpe,
                sharpe_ratio(&sample, case.risk_free, case.periods_per_year).unwrap(),
                tol,
            );
        }
        if case.sortino.is_some() {
            check(
                "sortino",
                case.sortino,
                sortino_ratio(&sample, case.risk_free, case.periods_per_year).unwrap(),
                tol,
            );
        }
        if case.historical_var.is_some() {
            check(
                "historical_var",
                case.historical_var,
                historical_var(&sample, case.confidence).unwrap(),
                tol,
            );
        }
        if case.historical_es.is_some() {
            check(
                "historical_es",
                case.historical_es,
                historical_es(&sample, case.confidence).unwrap(),
                tol,
            );
        }
        if case.parametric_var.is_some() {
            check(
                "parametric_var",
                case.parametric_var,
                parametric_var(&sample, case.confidence).unwrap(),
                tol,
            );
        }
        if case.parametric_es.is_some() {
            check(
                "parametric_es",
                case.parametric_es,
                parametric_es(&sample, case.confidence).unwrap(),
                tol,
            );
        }
        if case.cornish_fisher_var.is_some() {
            check(
                "cornish_fisher_var",
                case.cornish_fisher_var,
                cornish_fisher_var(&sample, case.confidence).unwrap(),
                tol,
            );
        }

        // Drawdown / Calmar require the price series.
        if let Some(prices) = &case.prices {
            let dd = max_drawdown(prices).unwrap();
            check("max_drawdown", case.max_drawdown, dd.max_drawdown, tol);
            if let Some(expected_dur) = case.max_drawdown_duration {
                assert_eq!(
                    dd.duration, expected_dur,
                    "case {}: drawdown duration {} != {}",
                    case.name, dd.duration, expected_dur
                );
            }
            if case.calmar.is_some() {
                check(
                    "calmar",
                    case.calmar,
                    oxis_stats::calmar_ratio(prices, case.periods_per_year).unwrap(),
                    tol,
                );
            }
        }

        // Relational / active-return metrics require the benchmark.
        if let Some(bench) = &case.benchmark {
            check(
                "covariance",
                case.covariance,
                covariance(&sample, bench).unwrap(),
                tol,
            );
            check(
                "correlation",
                case.correlation,
                correlation(&sample, bench).unwrap(),
                tol,
            );
            check("beta", case.beta, beta(&sample, bench).unwrap(), tol);
            check(
                "tracking_error",
                case.tracking_error,
                tracking_error(&sample, bench, case.periods_per_year).unwrap(),
                tol,
            );
            check(
                "information_ratio",
                case.information_ratio,
                information_ratio(&sample, bench, case.periods_per_year).unwrap(),
                tol,
            );
        }

        // Autocorrelation function.
        if let (Some(lags), Some(expected)) = (&case.acf_lags, &case.acf) {
            let got = acf(&sample, *lags.iter().max().unwrap()).unwrap();
            for (lag, exp) in lags.iter().zip(expected.iter()) {
                check(&format!("acf[{lag}]"), Some(*exp), got[*lag], tol);
            }
        }
    }

    eprintln!(
        "validated {} stats cases vs {} {} — worst |Δ| {worst:.3e}",
        reference.cases.len(),
        reference.oracle,
        reference.oracle_version,
    );
}
